### PR TITLE
Bugfix: dont use this in closure

### PR DESCRIPTION
**Pull request by Undergrounder**
Seems to have problems in PHP 5.3

### CODE REVIEW

**Comment by mattab** [comment]
Hi @Undergrounder 

Thanks for the PR. Could you rebase the PR, or open a new one? we cannot merge this one (conflicts). Thanks

**Comment by Undergrounder** [comment]
Rebased,

**Comment by mattab** [comment]
Thanks @Undergrounder we will review & hopefully merge in next days/weeks :+1:

**Comment by mattab** [comment]
:+1:

**Pull request merged**
